// Frozen seed for the 1791158400000 migration. Do not change after deployment.
export interface ProvinceSeed {
  id: number;
  nameTh: string;
  centerLatitude: number;
  centerLongitude: number;
  aliases: readonly string[];
}

// DOPA province codes/names: https://std.moc.go.th/std/group/28
// Coordinates stay in this frozen seed so the original migration and the
// drop-office-pin down migration can rebuild columns. The app does not read them.
// Approximate WGS84 positions adapted from Open Admin Data, CC BY 4.0:
// https://github.com/open-admin-data/thailand-administrative-divisions
export const PROVINCE_SEEDS: readonly ProvinceSeed[] = [
  {
    id: 10,
    nameTh: 'กรุงเทพมหานคร',
    centerLatitude: 13.753,
    centerLongitude: 100.5,
    aliases: ['กทม', 'กทม.', 'กรุงเทพ', 'กรุงเทพฯ', 'บางกอก'],
  },
  {
    id: 11,
    nameTh: 'สมุทรปราการ',
    centerLatitude: 13.656,
    centerLongitude: 100.533,
    aliases: [],
  },
  {
    id: 12,
    nameTh: 'นนทบุรี',
    centerLatitude: 13.914,
    centerLongitude: 100.422,
    aliases: [],
  },
  {
    id: 13,
    nameTh: 'ปทุมธานี',
    centerLatitude: 14.031,
    centerLongitude: 100.552,
    aliases: [],
  },
  {
    id: 14,
    nameTh: 'พระนครศรีอยุธยา',
    centerLatitude: 14.328,
    centerLongitude: 100.404,
    aliases: ['อยุธยา'],
  },
  {
    id: 15,
    nameTh: 'อ่างทอง',
    centerLatitude: 14.588,
    centerLongitude: 100.459,
    aliases: [],
  },
  {
    id: 16,
    nameTh: 'ลพบุรี',
    centerLatitude: 14.802,
    centerLongitude: 100.611,
    aliases: [],
  },
  {
    id: 17,
    nameTh: 'สิงห์บุรี',
    centerLatitude: 14.89,
    centerLongitude: 100.404,
    aliases: [],
  },
  {
    id: 18,
    nameTh: 'ชัยนาท',
    centerLatitude: 15.263,
    centerLongitude: 100.041,
    aliases: [],
  },
  {
    id: 19,
    nameTh: 'สระบุรี',
    centerLatitude: 14.586,
    centerLongitude: 101.002,
    aliases: [],
  },
  {
    id: 20,
    nameTh: 'ชลบุรี',
    centerLatitude: 12.611,
    centerLongitude: 100.889,
    aliases: [],
  },
  {
    id: 21,
    nameTh: 'ระยอง',
    centerLatitude: 12.646,
    centerLongitude: 101.171,
    aliases: [],
  },
  {
    id: 22,
    nameTh: 'จันทบุรี',
    centerLatitude: 12.465,
    centerLongitude: 102.066,
    aliases: [],
  },
  {
    id: 23,
    nameTh: 'ตราด',
    centerLatitude: 11.817,
    centerLongitude: 102.397,
    aliases: [],
  },
  {
    id: 24,
    nameTh: 'ฉะเชิงเทรา',
    centerLatitude: 13.707,
    centerLongitude: 101.1,
    aliases: [],
  },
  {
    id: 25,
    nameTh: 'ปราจีนบุรี',
    centerLatitude: 14.057,
    centerLongitude: 101.374,
    aliases: [],
  },
  {
    id: 26,
    nameTh: 'นครนายก',
    centerLatitude: 14.204,
    centerLongitude: 101.219,
    aliases: [],
  },
  {
    id: 27,
    nameTh: 'สระแก้ว',
    centerLatitude: 13.68,
    centerLongitude: 102.517,
    aliases: [],
  },
  {
    id: 30,
    nameTh: 'นครราชสีมา',
    centerLatitude: 14.909,
    centerLongitude: 101.851,
    aliases: ['โคราช'],
  },
  {
    id: 31,
    nameTh: 'บุรีรัมย์',
    centerLatitude: 14.999,
    centerLongitude: 103.104,
    aliases: [],
  },
  {
    id: 32,
    nameTh: 'สุรินทร์',
    centerLatitude: 14.884,
    centerLongitude: 103.49,
    aliases: [],
  },
  {
    id: 33,
    nameTh: 'ศรีสะเกษ',
    centerLatitude: 14.669,
    centerLongitude: 104.271,
    aliases: [],
  },
  {
    id: 34,
    nameTh: 'อุบลราชธานี',
    centerLatitude: 15.244,
    centerLongitude: 104.894,
    aliases: [],
  },
  {
    id: 35,
    nameTh: 'ยโสธร',
    centerLatitude: 15.799,
    centerLongitude: 104.148,
    aliases: [],
  },
  {
    id: 36,
    nameTh: 'ชัยภูมิ',
    centerLatitude: 16.61,
    centerLongitude: 101.921,
    aliases: [],
  },
  {
    id: 37,
    nameTh: 'อำนาจเจริญ',
    centerLatitude: 15.823,
    centerLongitude: 104.562,
    aliases: [],
  },
  {
    id: 38,
    nameTh: 'บึงกาฬ',
    centerLatitude: 18.031,
    centerLongitude: 103.711,
    aliases: [],
  },
  {
    id: 39,
    nameTh: 'หนองบัวลำภู',
    centerLatitude: 17.308,
    centerLongitude: 102.117,
    aliases: [],
  },
  {
    id: 40,
    nameTh: 'ขอนแก่น',
    centerLatitude: 16.035,
    centerLongitude: 102.723,
    aliases: [],
  },
  {
    id: 41,
    nameTh: 'อุดรธานี',
    centerLatitude: 17.411,
    centerLongitude: 102.792,
    aliases: [],
  },
  {
    id: 42,
    nameTh: 'เลย',
    centerLatitude: 17.493,
    centerLongitude: 101.732,
    aliases: [],
  },
  {
    id: 43,
    nameTh: 'หนองคาย',
    centerLatitude: 17.89,
    centerLongitude: 102.761,
    aliases: [],
  },
  {
    id: 44,
    nameTh: 'มหาสารคาม',
    centerLatitude: 16.162,
    centerLongitude: 103.484,
    aliases: [],
  },
  {
    id: 45,
    nameTh: 'ร้อยเอ็ด',
    centerLatitude: 15.6,
    centerLongitude: 104.139,
    aliases: [],
  },
  {
    id: 46,
    nameTh: 'กาฬสินธุ์',
    centerLatitude: 16.266,
    centerLongitude: 103.737,
    aliases: [],
  },
  {
    id: 47,
    nameTh: 'สกลนคร',
    centerLatitude: 17.125,
    centerLongitude: 104.26,
    aliases: [],
  },
  {
    id: 48,
    nameTh: 'นครพนม',
    centerLatitude: 17.066,
    centerLongitude: 104.749,
    aliases: [],
  },
  {
    id: 49,
    nameTh: 'มุกดาหาร',
    centerLatitude: 16.53,
    centerLongitude: 104.724,
    aliases: [],
  },
  {
    id: 50,
    nameTh: 'เชียงใหม่',
    centerLatitude: 18.785,
    centerLongitude: 98.985,
    aliases: [],
  },
  {
    id: 51,
    nameTh: 'ลำพูน',
    centerLatitude: 18.537,
    centerLongitude: 98.933,
    aliases: [],
  },
  {
    id: 52,
    nameTh: 'ลำปาง',
    centerLatitude: 18.752,
    centerLongitude: 99.996,
    aliases: [],
  },
  {
    id: 53,
    nameTh: 'อุตรดิตถ์',
    centerLatitude: 17.652,
    centerLongitude: 100.039,
    aliases: [],
  },
  {
    id: 54,
    nameTh: 'แพร่',
    centerLatitude: 18.14,
    centerLongitude: 100.142,
    aliases: [],
  },
  {
    id: 55,
    nameTh: 'น่าน',
    centerLatitude: 18.793,
    centerLongitude: 100.786,
    aliases: [],
  },
  {
    id: 56,
    nameTh: 'พะเยา',
    centerLatitude: 19.172,
    centerLongitude: 99.894,
    aliases: [],
  },
  {
    id: 57,
    nameTh: 'เชียงราย',
    centerLatitude: 19.907,
    centerLongitude: 99.832,
    aliases: [],
  },
  {
    id: 58,
    nameTh: 'แม่ฮ่องสอน',
    centerLatitude: 19.302,
    centerLongitude: 97.97,
    aliases: [],
  },
  {
    id: 60,
    nameTh: 'นครสวรรค์',
    centerLatitude: 15.896,
    centerLongitude: 100.315,
    aliases: [],
  },
  {
    id: 61,
    nameTh: 'อุทัยธานี',
    centerLatitude: 15.371,
    centerLongitude: 99.9,
    aliases: [],
  },
  {
    id: 62,
    nameTh: 'กำแพงเพชร',
    centerLatitude: 16.473,
    centerLongitude: 99.528,
    aliases: [],
  },
  {
    id: 63,
    nameTh: 'ตาก',
    centerLatitude: 16.862,
    centerLongitude: 99.129,
    aliases: [],
  },
  {
    id: 64,
    nameTh: 'สุโขทัย',
    centerLatitude: 17.012,
    centerLongitude: 99.822,
    aliases: [],
  },
  {
    id: 65,
    nameTh: 'พิษณุโลก',
    centerLatitude: 16.789,
    centerLongitude: 100.25,
    aliases: [],
  },
  {
    id: 66,
    nameTh: 'พิจิตร',
    centerLatitude: 16.222,
    centerLongitude: 100.427,
    aliases: [],
  },
  {
    id: 67,
    nameTh: 'เพชรบูรณ์',
    centerLatitude: 16.839,
    centerLongitude: 101.239,
    aliases: [],
  },
  {
    id: 70,
    nameTh: 'ราชบุรี',
    centerLatitude: 13.816,
    centerLongitude: 99.873,
    aliases: [],
  },
  {
    id: 71,
    nameTh: 'กาญจนบุรี',
    centerLatitude: 13.954,
    centerLongitude: 99.752,
    aliases: [],
  },
  {
    id: 72,
    nameTh: 'สุพรรณบุรี',
    centerLatitude: 14.85,
    centerLongitude: 99.988,
    aliases: [],
  },
  {
    id: 73,
    nameTh: 'นครปฐม',
    centerLatitude: 13.787,
    centerLongitude: 100.192,
    aliases: [],
  },
  {
    id: 74,
    nameTh: 'สมุทรสาคร',
    centerLatitude: 13.533,
    centerLongitude: 100.276,
    aliases: [],
  },
  {
    id: 75,
    nameTh: 'สมุทรสงคราม',
    centerLatitude: 13.487,
    centerLongitude: 99.958,
    aliases: [],
  },
  {
    id: 76,
    nameTh: 'เพชรบุรี',
    centerLatitude: 13.121,
    centerLongitude: 99.9,
    aliases: [],
  },
  {
    id: 77,
    nameTh: 'ประจวบคีรีขันธ์',
    centerLatitude: 11.805,
    centerLongitude: 99.784,
    aliases: [],
  },
  {
    id: 80,
    nameTh: 'นครศรีธรรมราช',
    centerLatitude: 9.324,
    centerLongitude: 99.775,
    aliases: [],
  },
  {
    id: 81,
    nameTh: 'กระบี่',
    centerLatitude: 8.049,
    centerLongitude: 98.676,
    aliases: [],
  },
  {
    id: 82,
    nameTh: 'พังงา',
    centerLatitude: 9.406,
    centerLongitude: 97.901,
    aliases: [],
  },
  {
    id: 83,
    nameTh: 'ภูเก็ต',
    centerLatitude: 7.924,
    centerLongitude: 98.455,
    aliases: [],
  },
  {
    id: 84,
    nameTh: 'สุราษฎร์ธานี',
    centerLatitude: 9.708,
    centerLongitude: 99.675,
    aliases: [],
  },
  {
    id: 85,
    nameTh: 'ระนอง',
    centerLatitude: 9.401,
    centerLongitude: 98.392,
    aliases: [],
  },
  {
    id: 86,
    nameTh: 'ชุมพร',
    centerLatitude: 10.459,
    centerLongitude: 99.403,
    aliases: [],
  },
  {
    id: 90,
    nameTh: 'สงขลา',
    centerLatitude: 7.561,
    centerLongitude: 100.356,
    aliases: [],
  },
  {
    id: 91,
    nameTh: 'สตูล',
    centerLatitude: 6.546,
    centerLongitude: 99.706,
    aliases: [],
  },
  {
    id: 92,
    nameTh: 'ตรัง',
    centerLatitude: 7.033,
    centerLongitude: 99.449,
    aliases: [],
  },
  {
    id: 93,
    nameTh: 'พัทลุง',
    centerLatitude: 7.589,
    centerLongitude: 100.05,
    aliases: [],
  },
  {
    id: 94,
    nameTh: 'ปัตตานี',
    centerLatitude: 6.87,
    centerLongitude: 101.256,
    aliases: [],
  },
  {
    id: 95,
    nameTh: 'ยะลา',
    centerLatitude: 6.464,
    centerLongitude: 101.374,
    aliases: [],
  },
  {
    id: 96,
    nameTh: 'นราธิวาส',
    centerLatitude: 6.424,
    centerLongitude: 101.82,
    aliases: [],
  },
];
